site/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'IndexController@index'));
Route::get('/listado', array('as' => 'search', 'uses' => 'SearchController@search'));

Route::get('/contacto', array('as' => 'contacto', 'uses' => 'MailController@contact'));
Route::post('/contacto', array('uses' => 'MailController@contact'));

// Sugerir comercio
Route::get('/sugeri', array('as' => 'sugeri', 'uses' => 'MailController@suggest'));
Route::post('/sugeri', array('uses' => 'MailController@suggest'));

Route::get('empresa/{id}/{slug}', array('as' => 'shop.view', 'uses' => 'ShopController@show'));

Route::get('/acerca', function()
{
    return View::make('acerca');
});

// Rutas de Admin
Route::group(['middleware' => 'auth'], function () {

    Route::get('admin', 'AdminController@index');
    Route::resource('admin/category', 'CategoryController');
    Route::resource('admin/service', 'ServiceController');

    // Shops
    Route::get('admin/shop/{id}/duplicate', array('as' => 'admin.shop.duplicate', 'uses' => 'ShopController@duplicate'));
    Route::resource('admin/shop', 'ShopController');

});


// Rutas de Autentificación
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Password Reset Routes...
Route::get('password/reset/{token?}', ['as' => 'auth.password.reset', 'uses' => 'Auth\PasswordController@showResetForm']);
Route::post('password/email', ['as' => 'auth.password.email', 'uses' => 'Auth\PasswordController@sendResetLinkEmail']);
Route::post('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\PasswordController@reset']);

site/resources/views/admin/categories.blade.php
@extends('admin/app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Categorías de servicios</div>

                <div class="panel-body">

                  @if (Session::has('message'))
                      <div class="alert alert-info">{{ Session::get('message') }}</div>
                  @endif

                  <ul>
                    @foreach ($categories as $cat)
                      <li>
                        <a href="{{ URL::route('admin.category.edit', $cat->id) }}"
                           class="btn btn-link">
                          {{ $cat->name }}
                        </a>
                      </li>
                    @endforeach
                  </ul>
                    <hr>
                  <div>
                      <a href="{{ URL::route('admin.category.create') }}"
                         class="btn btn-default" role="button">
                        Crear Categoría
                      </a>
                  </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

site/resources/views/admin/index.blade.php
@extends('admin/app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Administración</div>

                <div class="panel-body">
                    <h2>Últimas empresas creadas</h2>

                    @if (count($shops) > 0)
                    <ul>
                        @foreach ($shops as $s)
                        <li>
                          <a href="{{ route('admin.shop.edit', $s->id) }}">{{ $s->name }}</a>
                          <small>{{ date("d/m/Y H:i", strtotime( $s->created_at )) }}</small>
                        </li>
                        @endforeach
                    </ul>
                    @else
                    <p>
                      Aún no hay contenido creado...
                    </p>
                    <p>
                      <a class="btn btn-default" href="/admin/shop/create"
                         role="button">Crear Empresas</a>
                    </p>
                    @endif

                    Empresas creadas: <strong>{{$total}}</strong>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

site/resources/views/admin/service_create.blade.php
@extends('admin/app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Añadir Servicio</div>

                    <div class="panel-body">

                        @if(Session::has('message'))
                            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                        @endif

                        {!! HTML::ul($errors->all()) !!}

                        {!! BootForm::open()->post()->action(route('admin.service.store')) !!}

                        <div class="form-group {{ $errors->has('category') ? ' has-error' : '' }}">
                            {!! BootForm::select('Categoría', 'service-category')
                                ->options(['1' => 'Rubro', '2' => 'Tarea', '3' => 'Pieza', '4' => 'Terminaciones', '5' => 'Material'])
                                ->select(Input::old('category')) !!}
                        </div>

                        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                            {!! BootForm::text('Nombre', 'service-name')->required() !!}
                        </div>

                        {!! BootForm::submit('Guardar')->class('btn btn-primary') !!}
                        {!! BootForm::close() !!}


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

site/resources/views/admin/service_edit.blade.php
@extends('admin/app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Editar Servicio ({!! $service->name !!})</div>

                    <div class="panel-body">

                        {!! HTML::ul($errors->all()) !!}

                        {!! BootForm::open()->put()->action(route('admin.service.update', ['id' => $service->id])) !!}

                        <div class="form-group {{ $errors->has('service-name') ? ' has-error' : '' }}">
                            {!! BootForm::text('Nombre', 'service-name')->required()->defaultValue($service->name) !!}
                        </div>

                        <div class="form-group {{ $errors->has('service-category') ? ' has-error' : '' }}">
                            {!! BootForm::select('Categoría', 'service-category')
                                ->options(['1' => 'Rubro', '2' => 'Tarea', '3' => 'Pieza', '4' => 'Terminaciones', '5' => 'Material'])
                                ->select($service->category_id) !!}
                        </div>

                        {!! BootForm::submit('Guardar')->class('btn btn-primary') !!}
                        {!! BootForm::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

site/resources/views/admin/services.blade.php
@extends('admin/app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if (Session::has('flash_message'))
                <div class="alert alert-warning alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  {{ Session::get('flash_message') }}
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">Servicios (Total: <?php echo $services->total() ?>)</div>

                <div class="panel-body">

                  <div class="table-responsive">
                    <table class="table table-striped table-shops">
                      <thead>
                        <tr>
                          <th>Categoría</th>
                          <th>Nombre</th>
                          <th>Acción</th>
                        </tr>
                      </thead>

                      <tbody>
                      @foreach ($services as $s)
                      <tr>
                          <td scope="row">{{ $s->category->name }}</td>
                          <td>{{ $s->name }}</td>
                          <td class="td-actions">

                            <a class="btn btn-default btn-sm" href="{{ route('admin.service.edit', $s->id) }}">&#9998; Editar</a>

                            {!! BootForm::open()->delete()->class('delete-form js-delete-shop-form')->action(route('admin.service.destroy',
                                ['id' => $s->id])) !!}
                              <input class="btn btn-danger btn-sm" type="submit" value="&times;" />
                            {!! BootForm::close() !!}
                          </td>
                        </tr>
                      @endforeach
                      </tbody>
                    </table>
                  </div>

                </div>
            </div>
            {!! $services->render() !!}
        </div>
    </div>
</div>
@endsection

site/resources/views/admin/shop_create.blade.php
@extends('admin/app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Añadir Empresa</div>

                    <div class="panel-body">

                        {!! HTML::ul($errors->all()) !!}

                        {!! BootForm::open()->multipart()->post()->action(route('admin.shop.store')) !!}

                        <div class="row">
                            <div class="form-group col-md-6 {{ $errors->has('name') ? ' has-error' : '' }}">
                                {!! BootForm::text('Nombre', 'shop-name')->required() !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('address') ? ' has-error' : '' }}">
                                {!! BootForm::text('Dirección', 'shop-address')->required() !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('opening_hours') ? ' has-error' : '' }}">
                                {!! BootForm::text('Horario', 'shop-opening_hours') !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('phone') ? ' has-error' : '' }}">
                                {!! BootForm::text('Teléfono', 'shop-phone')->required() !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('website') ? ' has-error' : '' }}">
                                {!! BootForm::text('Sitio Web', 'shop-website') !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('email') ? ' has-error' : '' }}">
                                {!! BootForm::email('E-mail', 'shop-email') !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('logo') ? ' has-error' : '' }}">
                                {!! BootForm::file('Logo', 'shop-logo') !!}
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="shop-logo-current">Ubicación</label>
                                    <div class="map-select">
                                        <div class="map"></div>
                                        <div class="row form-group">
                                            <div class="col-xs-9">
                                                <input type="text" name="search-address" class="search-address form-control" placeholder="Buscar dirección" value="">
                                            </div>
                                            <div class="col-xs-3">
                                                <button type="button" class="btn btn-secondary btn-block js-search-address">Buscar</button>
                                            </div>
                                        </div>
                                        <div class="row form-group">
                                            <div class="col-md-6">
                                                <input type="text" class="form-control js-shop-lat" name="shop-lat" placeholder="Latitud">
                                            </div>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control js-shop-lng" name="shop-lng" placeholder="Longitud">
                                            </div>
                                        </div>
                                        <button type="button" class="btn btn-primary js-reset-location">Borrar Ubicación</button>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-md-6 {{ $errors->has('featured') ? ' has-error' : '' }}">
                                <label class="control-label" for="shop-featured">Opciones</label>
                                {!! BootForm::checkbox('Destacado en portada', 'shop-featured') !!}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('category') ? ' has-error' : '' }}">
                                    <label class="control-label" for="shop-services">Servicios Asociados</label>
                                    <select multiple class="text-input form-control js-services" name="shopServices[]" style="width: 100%">
                                        <optgroup label="Rubros">
                                            @foreach($services['Rubros'] as $key => $s)
                                                <option value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Tareas">
                                            @foreach($services['Tareas'] as $key => $s)
                                                <option value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Tareas">
                                            @foreach($services['Tareas'] as $key => $s)
                                                <option value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Piezas">
                                            @foreach($services['Piezas'] as $key => $s)
                                                <option value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Terminaciones">
                                            @foreach($services['Terminaciones'] as $key => $s)
                                                <option value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Materiales">
                                            @foreach($services['Materiales'] as $key => $s)
                                                <option value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {!! BootForm::submit('Guardar')->class('btn btn-primary') !!}
                            </div>
                        </div>
                        {!! BootForm::close() !!}


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

site/resources/views/admin/shop_edit.blade.php
@extends('admin/app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Editar Empresa ({!! $shop->name !!})</div>

                    <div class="panel-body">

                        {!! HTML::ul($errors->all()) !!}

                        {!! BootForm::open()->multipart()->put()->action(route('admin.shop.update', ['id' => $shop->id])) !!}

                        <div class="row">
                            <div class="form-group col-md-6 {{ $errors->has('name') ? ' has-error' : '' }}">
                                {!! BootForm::text('Nombre', 'shop-name')->required()->defaultValue($shop->name) !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('address') ? ' has-error' : '' }}">
                                {!! BootForm::text('Dirección', 'shop-address')->required()->defaultValue($shop->address) !!}
                            </div>
                            <div class="form-group form-group col-md-6 {{ $errors->has('opening_hours') ? ' has-error' : '' }}">
                                {!! BootForm::text('Horario', 'shop-opening_hours')->defaultValue($shop->opening_hours) !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('phone') ? ' has-error' : '' }}">
                                {!! BootForm::text('Teléfono', 'shop-phone')->required()->defaultValue($shop->phone) !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('website') ? ' has-error' : '' }}">
                                {!! BootForm::text('Sitio Web', 'shop-website')->defaultValue($shop->website) !!}
                            </div>
                            <div class="form-group col-md-6 {{ $errors->has('email') ? ' has-error' : '' }}">
                                {!! BootForm::email('E-mail', 'shop-email')->defaultValue($shop->email) !!}
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('logo') ? ' has-error' : '' }}">
                                    {!! BootForm::file('Logo', 'shop-logo') !!}
                                </div>

                                @if($shop->logo)
                                    <div class="form-group">
                                        <label class="control-label" for="shop-logo-current">Logo Actual</label>
                                        <div class="current-logo-wrap">
                                            <img class="current-logo-img" src="/uploads/{{ $shop->logo }}" alt="Loco Actual" />
                                        </div>
                                    </div>
                                @endif
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="shop-logo-current">Ubicación</label>
                                    <div class="map-select">
                                        <div class="map"></div>
                                        <div class="row form-group">
                                            <div class="col-xs-9">
                                                <input type="text" name="search-address" class="search-address form-control" placeholder="Buscar dirección" value="">
                                            </div>
                                            <div class="col-xs-3">
                                                <button type="button" class="btn btn-secondary btn-block js-search-address">Buscar</button>
                                            </div>
                                        </div>
                                        <div class="row form-group">
                                            <div class="col-md-6">
                                                {!! BootForm::text('Latitud', 'shop-lat')->addClass('js-shop-lat')->defaultValue($shop->lat) !!}
                                            </div>
                                            <div class="col-md-6">
                                                {!! BootForm::text('Latitud', 'shop-lng')->addClass('js-shop-lng')->defaultValue($shop->lng) !!}
                                                {{-- <input type="text" class="form-control js-shop-lng" name="shop-lng" placeholder="Longitud"> --}}
                                            </div>
                                        </div>
                                        <button type="button" class="btn btn-primary js-reset-location">Borrar Ubicación</button>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('featured') ? ' has-error' : '' }}">
                                    <label class="control-label" for="shop-featured">Opciones</label>
                                    @if ($shop->featured)
                                        {!! BootForm::checkbox('Destacado en portada', 'shop-featured')->check() !!}
                                    @else
                                        {!! BootForm::checkbox('Destacado en portada', 'shop-featured')->uncheck() !!}
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('category') ? ' has-error' : '' }}">
                                    <label class="control-label" for="shop-services">Servicios Asociados</label>
    
                                    <select multiple class="text-input form-control js-services" name="shopServices[]" style="width: 100%">
                                        <optgroup label="Rubros">
                                            @foreach($services['Rubros'] as $key => $s)
                                                <option @if(in_array($s->id, $shopServices))selected="selected"@endif value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Tareas">
                                            @foreach($services['Tareas'] as $key => $s)
                                                <option @if(in_array($s->id, $shopServices))selected="selected"@endif value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Tareas">
                                            @foreach($services['Tareas'] as $key => $s)
                                                <option @if(in_array($s->id, $shopServices))selected="selected"@endif value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Piezas">
                                            @foreach($services['Piezas'] as $key => $s)
                                                <option @if(in_array($s->id, $shopServices))selected="selected"@endif value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Terminaciones">
                                            @foreach($services['Terminaciones'] as $key => $s)
                                                <option @if(in_array($s->id, $shopServices))selected="selected"@endif value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                        <optgroup label="Materiales">
                                            @foreach($services['Materiales'] as $key => $s)
                                                <option @if(in_array($s->id, $shopServices))selected="selected"@endif value="{{$s->id}}">{{$s->name}}</option>
                                            @endforeach
                                        </optgroup>
                                    </select>
                                </div>
                            </div>
                        </div>

                        {!! BootForm::submit('Guardar')->class('btn btn-primary') !!}
                        {!! BootForm::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

site/resources/views/admin/shops.blade.php
@extends('admin/app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if (Session::has('flash_message'))
                <div class="alert alert-warning alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  {{ Session::get('flash_message') }}
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">Empresas (Total: <?php echo $shops->total() ?>)</div>

                <div class="panel-body">
                  {!! BootForm::open()->get()->action('/admin/shop'); !!}
                    <div class="form-group">
                      <input type="text" name="q" class="form-control" placeholder="Buscar">
                    </div>
                  {!! BootForm::close() !!}

                  <div class="table-responsive">
                    <table class="table table-striped table-shops">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Logo</th>
                          <th>Nombre</th>
                          <th>Dirección</th>
                          <th>Horario</th>
                          <th>Teléfono</th>
                          <th>E-mail</th>
                          <th>Destacado?</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>

                      <tbody>
                      @foreach ($shops as $s)
                      <tr>
                          <th scope="row">{{ $s->id }}</th>
                          <td>
                            @if ($s->logo)
                              <a href="{{ route('admin.shop.edit', $s->id) }}">
                                <img class="current-logo-img table-thumb" src="/uploads/{{ $s->logo }}" alt="Logo" />
                              </a>
                            @endif
                          </td>
                          <td>{{ $s->name }}</td>
                          <td>{{ $s->address }}</td>
                          <td>{{ $s->opening_hours }}</td>
                          <td>{{ $s->phone }}</td>
                          <td>{{ $s->email }}</td>
                          <td>
                              @if ($s->featured)
                              ✅
                              @endif
                          </td>
                          <td class="td-actions">

                            <a title="Editar" class="btn btn-default btn-sm" href="{{ route('admin.shop.edit', $s->id) }}">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>

                            <a title="Clonar" class="btn btn-default btn-sm" href="{{ route('admin.shop.duplicate', $s->id) }}">
                                <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
                            </a>

                            <a title="Ver" target="_" class="btn btn-default btn-sm" href="{{ route('shop.view', [$s->id, $s->slug]) }}">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            </a>

                            {!! BootForm::open()->delete()->class('delete-form js-delete-shop-form')->action(route('admin.shop.destroy',
                                ['id' => $s->id])) !!}
                                <button type="submit" class="btn btn-danger btn-sm" name="button">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </button>
                            {!! BootForm::close() !!}
                          </td>
                        </tr>
                      @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
            </div>
            <?php echo $shops->appends(['q' => $query ])->render(); ?>
        </div>
    </div>
</div>
@endsection